name: Parse COT Data

on:
  schedule:
    - cron: '0 4 * * 6'  # Samedi 04:00 UTC (06:00 Paris)
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run COT parser
        run: |
          node scripts/parseCot.js

      - name: Commit updated COT data
        run: |
          git config --global user.name 'MacroPulse Bot'
          git config --global user.email 'bot@macropulse.ai'
          git add data/cot/*.json
          git commit -m "🔁 Weekly update COT data"
          git push
