name: Parse COT Data

on:
  schedule:
    - cron: '0 5 * * 6'  # Tous les samedis à 7h heure de Paris (UTC+2)
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run COT parser and send to Base44
        run: node scripts/fetch-cot-data.mjs
        env:
          BASE44_SECRET: ${{ secrets.BASE44_SECRET }}

      - name: Commit updated COT data
  run: |
    git config --global user.name 'MacroPulse Bot'
    git config --global user.email 'bot@macropulse.io'
    git pull --rebase
    git add data/cot-summary/*.json
    git commit -m "Weekly update COT data" || echo "No changes to commit"
    git push
